In [1]:
import numpy as np

In [2]:
valoraciones = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]]) # array de numpy el objeto mas popular de numpy
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [3]:
valoraciones[0][1] # acceder a elemento [fila][columna]

7

In [4]:
valoraciones[0,1] # [fila, columna]

7

In [5]:
valoraciones2 = np.array([[[8,7,8,5],[2,5,5,2]],[[2,6,8,4],[8,9,7,4]],[[8,8,9,3],[10,9,10,8]]]) #array de 3 dimensiones

In [6]:
valoraciones2  
#los valores representan 3 clientes que valoraron 4 productos en 2 años distintos

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [7]:
valoraciones2[0,1,2]

5

In [8]:
np.zeros((3,2,4)) # la misma estructura de arriba pero vacia

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [9]:
valoraciones2 + np.ones((3,2,4)) # le sumamos un uno a todos los elementos del array

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  6.,  6.,  3.]],

       [[ 3.,  7.,  9.,  5.],
        [ 9., 10.,  8.,  5.]],

       [[ 9.,  9., 10.,  4.],
        [11., 10., 11.,  9.]]])

In [10]:
np.mean(valoraciones2) # la media de todos los valores del array

6.458333333333333

In [11]:
np.mean(valoraciones2, axis=0) # axis especifica el eje en que queremos que ejecute la media

array([[6.        , 7.        , 8.33333333, 4.        ],
       [6.66666667, 7.66666667, 7.33333333, 4.66666667]])

In [12]:
np.mean(valoraciones2, axis=1)

array([[5. , 6. , 6.5, 3.5],
       [5. , 7.5, 7.5, 4. ],
       [9. , 8.5, 9.5, 5.5]])

In [13]:
np.mean(valoraciones2, axis=2)

array([[7.  , 3.5 ],
       [5.  , 7.  ],
       [7.  , 9.25]])

In [14]:
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],(3,2,2)) # convierte una lista a las dimensiones que queramos
# Nota: las dimensiones ingresadas al multiplicarse deben ajustarse al numero de elementos de la lista ingresada

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
np.median(df["Columna1"]) # median se puede usar sobre columnas de data frames para obtener su mediana

In [15]:
np.random.rand(2,2) # el modulo random permite generar objetos aleatorios
# rand genera un objeto de valores aleatorios entre 0 y 1 con las dimensiones ingresadas

array([[0.14105859, 0.79144091],
       [0.26801794, 0.75343722]])